"""add_leads_and_fate_matrix_tables

Revision ID: 551fd77e4215
Revises: b7c8d9e0f1a2
Create Date: 2026-02-04 00:28:10.534910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '551fd77e4215'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fate_matrix',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('designation_role', sa.Text(), nullable=False),
    sa.Column('f_pain', sa.Text(), nullable=False),
    sa.Column('a_goal', sa.Text(), nullable=False),
    sa.Column('t_solution', sa.Text(), nullable=False),
    sa.Column('e_evidence', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector', 'designation_role', name='fate_matrix_sector_designation_role_key')
    )
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('mobile_number', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('lead_stage', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), nullable=True),
    sa.Column('verification_tag', sa.Text(), nullable=True),
    sa.Column('enrichment_status', sa.Enum('pending', 'completed', 'failed', name='enrichment_status_enum'), server_default='pending', nullable=True),
    sa.Column('hiring_signal', sa.Boolean(), nullable=True),
    sa.Column('ai_variables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('scraped_data', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('personalized_intro', sa.Text(), nullable=True),
    sa.Column('email_1_subject', sa.Text(), nullable=True),
    sa.Column('email_1_body', sa.Text(), nullable=True),
    sa.Column('email_2_subject', sa.Text(), nullable=True),
    sa.Column('email_2_body', sa.Text(), nullable=True),
    sa.Column('email_3_subject', sa.Text(), nullable=True),
    sa.Column('email_3_body', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instantly_lead_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_lead_stage', 'leads', ['lead_stage'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['verification_status', 'is_sent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_lead_stage', table_name='leads')
    op.drop_table('leads')
    op.drop_table('fate_matrix')
    # ### end Alembic commands ###
