"""add_whatsapp_outreach_tables

Revision ID: 5696d32192e1
Revises: a1b2c3d4e5f6
Create Date: 2026-01-24 18:59:56.642667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5696d32192e1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mobile_number', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_lead_id', sa.BigInteger(), nullable=True),
    sa.Column('is_wa_sent', sa.Boolean(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_template_used', sa.Text(), nullable=True),
    sa.Column('last_delivery_status', sa.Text(), nullable=True),
    sa.Column('last_failed_reason', sa.Text(), nullable=True),
    sa.Column('wati_contact_id', sa.Text(), nullable=True),
    sa.Column('wati_conversation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index('idx_whatsapp_leads_created', 'whatsapp_leads', ['created_at'], unique=False)
    op.create_index('idx_whatsapp_leads_mobile', 'whatsapp_leads', ['mobile_number'], unique=False)
    op.create_index('idx_whatsapp_leads_sent', 'whatsapp_leads', ['is_wa_sent'], unique=False)
    op.create_index('idx_whatsapp_leads_source', 'whatsapp_leads', ['source'], unique=False)
    op.create_index('idx_whatsapp_leads_status', 'whatsapp_leads', ['last_delivery_status'], unique=False)
    op.create_table('whatsapp_activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('whatsapp_lead_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_name', sa.Text(), nullable=True),
    sa.Column('lead_mobile', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['whatsapp_lead_id'], ['whatsapp_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_whatsapp_activities_created', 'whatsapp_activities', ['created_at'], unique=False)
    op.create_index('idx_whatsapp_activities_global', 'whatsapp_activities', ['is_global'], unique=False)
    op.create_index('idx_whatsapp_activities_lead_id', 'whatsapp_activities', ['whatsapp_lead_id'], unique=False)
    op.create_index('idx_whatsapp_activities_type', 'whatsapp_activities', ['activity_type'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('whatsapp_lead_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('wati_message_id', sa.Text(), nullable=True),
    sa.Column('wati_conversation_id', sa.Text(), nullable=True),
    sa.Column('broadcast_name', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['whatsapp_lead_id'], ['whatsapp_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_whatsapp_messages_created', 'whatsapp_messages', ['created_at'], unique=False)
    op.create_index('idx_whatsapp_messages_direction', 'whatsapp_messages', ['direction'], unique=False)
    op.create_index('idx_whatsapp_messages_lead_id', 'whatsapp_messages', ['whatsapp_lead_id'], unique=False)
    op.create_index('idx_whatsapp_messages_status', 'whatsapp_messages', ['status'], unique=False)
    op.create_index('idx_whatsapp_messages_wati_id', 'whatsapp_messages', ['wati_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_whatsapp_messages_wati_id', table_name='whatsapp_messages')
    op.drop_index('idx_whatsapp_messages_status', table_name='whatsapp_messages')
    op.drop_index('idx_whatsapp_messages_lead_id', table_name='whatsapp_messages')
    op.drop_index('idx_whatsapp_messages_direction', table_name='whatsapp_messages')
    op.drop_index('idx_whatsapp_messages_created', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index('idx_whatsapp_activities_type', table_name='whatsapp_activities')
    op.drop_index('idx_whatsapp_activities_lead_id', table_name='whatsapp_activities')
    op.drop_index('idx_whatsapp_activities_global', table_name='whatsapp_activities')
    op.drop_index('idx_whatsapp_activities_created', table_name='whatsapp_activities')
    op.drop_table('whatsapp_activities')
    op.drop_index('idx_whatsapp_leads_status', table_name='whatsapp_leads')
    op.drop_index('idx_whatsapp_leads_source', table_name='whatsapp_leads')
    op.drop_index('idx_whatsapp_leads_sent', table_name='whatsapp_leads')
    op.drop_index('idx_whatsapp_leads_mobile', table_name='whatsapp_leads')
    op.drop_index('idx_whatsapp_leads_created', table_name='whatsapp_leads')
    op.drop_table('whatsapp_leads')
    # ### end Alembic commands ###
