"""add_mobile_number_to_linkedin_leads

Revision ID: 9cc777bb93e0
Revises: 5696d32192e1
Create Date: 2026-01-25 14:13:23.435454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc777bb93e0'
down_revision: Union[str, Sequence[str], None] = '5696d32192e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_outreach_leads', sa.Column('mobile_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_outreach_leads', 'mobile_number')
    # ### end Alembic commands ###
