"""create_linkedin_outreach_leads_table

Revision ID: c8c7442997aa
Revises: f3fe4bee76d9
Create Date: 2026-01-15 09:23:27.430070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8c7442997aa'
down_revision: Union[str, Sequence[str], None] = 'f3fe4bee76d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_outreach_leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('search_keyword', sa.Text(), nullable=True),
    sa.Column('post_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hiring_signal', sa.Boolean(), nullable=True),
    sa.Column('hiring_roles', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('ai_variables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('linkedin_dm', sa.Text(), nullable=True),
    sa.Column('is_dm_sent', sa.Boolean(), nullable=True),
    sa.Column('dm_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_url')
    )
    op.create_index('idx_linkedin_leads_dm_status', 'linkedin_outreach_leads', ['is_dm_sent'], unique=False)
    op.create_index('idx_linkedin_leads_hiring', 'linkedin_outreach_leads', ['hiring_signal'], unique=False)
    op.create_index('idx_linkedin_leads_keyword', 'linkedin_outreach_leads', ['search_keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_linkedin_leads_keyword', table_name='linkedin_outreach_leads')
    op.drop_index('idx_linkedin_leads_hiring', table_name='linkedin_outreach_leads')
    op.drop_index('idx_linkedin_leads_dm_status', table_name='linkedin_outreach_leads')
    op.drop_table('linkedin_outreach_leads')
    # ### end Alembic commands ###
